spring:
  datasource:
    url: jdbc:h2:mem:smarttask;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# If you prefer Postgres in docker-compose, replace datasource with env vars like:
# spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}

server:
  port: 8080

app:
  jwt:
    secret: change-me-if-production
    validity-ms: 3600000
